#ifndef JENKINS_H
#define JENKINS_H

#define BOARD_E100_LITE 0
#define BOARD_E100 1

#define CONFIG_BOARD_E100 BOARD_E100_LITE

#define JENKINS_COMMIT_ID "##JENKINS_COMMIT_ID##"
#define JENKINS_VERSION "##JENKINS_VERSION##"
#define JENKINS_CUSTOMER "##JENKINS_CUSTOMER##"
#define JENKINS_BOARD "##JENKINS_BOARD##"

#endif
