#ifndef __DEFINE_DEFAULT_H__
#define __DEFINE_DEFAULT_H__

// mcu
#define DEFAULT_MCU_SERIAL "/dev/serial/by-id/usb-Klipper_stm32f446xx_27001B000950534E4E313020-if00"
#define DEFAULT_MCU_CANBUS_UUID ""
#define DEFAULT_MCU_CANBUS_INTERFACE "can0"

// printer
#define DEFAULT_PRINTER_KINEMATICS "cartesian"
#define DEFAULT_PRINTER_MAX_VELOCITY 500.0 // 300.0
#define DEFAULT_PRINTER_MAX_ACCEL 10000.0  //--G-G-2022-08-23--------------3000.0
#define DEFAULT_PRINTER_MAX_Z_VELOCITY 5
#define DEFAULT_PRINTER_MAX_Z_ACCEL 800 // 100
#define DEFAULT_PRINTER_MINIMUM_Z_POSITION -20.0
#define DEFAULT_PRINTER_SQUARE_CORNER_VELOCITY 5

// safe_z_home
#define DEFAULT_HOME_XY_POSION "0.0,0.0"
#define DEFAULT_MOVE_XY_SPEED 100
#define DEFAULT_Z_HOP 0.0

// heater bed
#define DEFAULT_HEATER_BED_NAME "bed"
#define DEFAULT_HEATER_BED_HEATER_PIN "PC0"
#define DEFAULT_HEATER_BED_SENSOR_PIN "PB14"
#define DEFAULT_HEATER_BED_SENSOR_TYPE "ATC Semitec 104GT-2"
#define DEFAULT_HEATER_BED_CONTROL "watermark"
#define DEFAULT_HEATER_BED_MIN_TEMP 0
#define DEFAULT_HEATER_BED_MAX_TEMP 130 // 130

// fan
#define DEFAULT_FAN_PIN "PG17"
#define DEFAULT_FAN_HARDWARE_PWM "true"
#define DEFAULT_FAN_SPEED 77.0

// heater_fan
#define DEFAULT_HEATER_FAN_PIN "PG16"

// fan_generic
#define DEFAULT_FAN_GENERIC_PIN_1 "PG18"
#define DEFAULT_FAN_GENERIC_PIN_2 "PC1"

//PROBE
#define DEFAULT_PROBE_Z_OFFSET -3.6

// stepper X
#define DEFAULT_STEPPER_X_STEP_PIN "PF3"
#define DEFAULT_STEPPER_X_DIR_PIN "PF5" // M8002 I-1   X步进电机方向
#define DEFAULT_STEPPER_X_ENABLE_PIN "PF1"
#define DEFAULT_STEPPER_X_ENDSTOP_PIN "PG2"
#define DEFAULT_STEPPER_X_MICROSTEPS 16               // 16细分
#define DEFAULT_STEPPER_X_GEAR_RATIO ""               // 减速电机减速比
#define DEFAULT_STEPPER_X_FULL_STEPS_PER_ROTATION 200 //(360/1.8)  电机200步每圈  200*16=3200微步每圈
#define DEFAULT_STEPPER_X_STEP_DISTANCE -1
#define DEFAULT_STEPPER_X_ROTATION_DISTANCE 32 //(20*2.032)  齿数*齿距 电机转一圈皮带前进距离  M8009 S0.01061083   M8009 X0.010625  Y0.010625
#define DEFAULT_STEPPER_X_POSITION_ENDSTOP 0
#define DEFAULT_STEPPER_X_POSITION_MIN 0
#define DEFAULT_STEPPER_X_POSITION_MAX 235
#define DEFAULT_STEPPER_X_HOMING_SPEED 50
#define DEFAULT_STEPPER_X_SECOND_HOMING_SPEED 5
#define DEFAULT_STEPPER_X_HOMING_RETRACT_DIST 5
#define DEFAULT_STEPPER_X_HOMING_POSITIVE_DIR 0
#define DEFAULT_STEPPER_X_POSITION_ENDSTOP 0

// stepper Y
#define DEFAULT_STEPPER_Y_STEP_PIN "PG9"
#define DEFAULT_STEPPER_Y_DIR_PIN "PF0" // M8003 I-1   Y步进电机方向
#define DEFAULT_STEPPER_Y_ENABLE_PIN "PG8"
#define DEFAULT_STEPPER_Y_ENDSTOP_PIN "PE13"
#define DEFAULT_STEPPER_Y_MICROSTEPS 16
#define DEFAULT_STEPPER_Y_GEAR_RATIO ""
#define DEFAULT_STEPPER_Y_FULL_STEPS_PER_ROTATION 200
#define DEFAULT_STEPPER_Y_STEP_DISTANCE -1
#define DEFAULT_STEPPER_Y_ROTATION_DISTANCE 32
#define DEFAULT_STEPPER_Y_POSITION_ENDSTOP 0
#define DEFAULT_STEPPER_Y_POSITION_MIN 0
#define DEFAULT_STEPPER_Y_POSITION_MAX 235
#define DEFAULT_STEPPER_Y_HOMING_SPEED 50
#define DEFAULT_STEPPER_Y_SECOND_HOMING_SPEED 5
#define DEFAULT_STEPPER_Y_HOMING_RETRACT_DIST 5
#define DEFAULT_STEPPER_Y_HOMING_POSITIVE_DIR 0

// stepper Z
#define DEFAULT_STEPPER_Z_RAIL_NAME "stepper_z"
#define DEFAULT_STEPPER_Z_STEP_PIN "PG15"
#define DEFAULT_STEPPER_Z_DIR_PIN "PG14" // M8004 I1   Z步进电机方向
#define DEFAULT_STEPPER_Z_ENABLE_PIN "PG13"
#define DEFAULT_STEPPER_Z_ENDSTOP_PIN "PD22"
#define DEFAULT_STEPPER_Z_MICROSTEPS 16
#define DEFAULT_STEPPER_Z_FULL_STEPS_PER_ROTATION 200
#define DEFAULT_STEPPER_Z_STEP_DISTANCE -1
#define DEFAULT_STEPPER_Z_ROTATION_DISTANCE 8.0 // 导程 螺杆转一圈平台上升的高度
#define DEFAULT_STEPPER_Z_POSITION_ENDSTOP 3.6
#define DEFAULT_STEPPER_Z_POSITION_MIN 0
#define DEFAULT_STEPPER_Z_POSITION_MAX 250
#define DEFAULT_STEPPER_Z_HOMING_SPEED 5
#define DEFAULT_STEPPER_Z_SECOND_HOMING_SPEED 5
#define DEFAULT_STEPPER_Z_HOMING_RETRACT_DIST 5
#define DEFAULT_STEPPER_Z_HOMING_POSITIVE_DIR 0
#define DEFAULT_STEPPER_Z_GEAR_RATIO "40:16"

#define DEFAULT_STEPPER_EXT_NUM 3
#define DEFAULT_STEPPER_TOTAL_NUM 7

// stepper Z1
#define DEFAULT_STEPPER_Z1_RAIL_NAME "stepper_z1"
#define DEFAULT_STEPPER_Z1_STEP_PIN "PB6"
#define DEFAULT_STEPPER_Z1_DIR_PIN "PB5" // M8004 I1   Z步进电机方向
#define DEFAULT_STEPPER_Z1_ENABLE_PIN "!PB7"
#define DEFAULT_STEPPER_Z1_ENDSTOP_PIN "PC0"

// stepper Z2
#define DEFAULT_STEPPER_Z2_RAIL_NAME "stepper_z2"
#define DEFAULT_STEPPER_Z2_STEP_PIN "PD15"
#define DEFAULT_STEPPER_Z2_DIR_PIN "PB3" // M8004 I1   Z步进电机方向
#define DEFAULT_STEPPER_Z2_ENABLE_PIN "!PB4"
#define DEFAULT_STEPPER_Z2_ENDSTOP_PIN "PC0"

// stepper Z3
#define DEFAULT_STEPPER_Z3_RAIL_NAME "stepper_z3"
#define DEFAULT_STEPPER_Z3_STEP_PIN "PD11"
#define DEFAULT_STEPPER_Z3_DIR_PIN "PD12" // M8004 I1   Z步进电机方向
#define DEFAULT_STEPPER_Z3_ENABLE_PIN "!PD13"
#define DEFAULT_STEPPER_Z3_ENDSTOP_PIN "PC0"

// extruder
#define DEFAULT_HEATER_EXTRUDER_NAME "extruder"
#define DEFAULT_EXTRUDER_STEP_PIN "PG4"
#define DEFAULT_EXTRUDER_DIR_PIN "PG12" // M8005 I-1   E E2 E3步进电机方向  M8005 I1 E2  M8005 I1 E3
#define DEFAULT_EXTRUDER_ENABLE_PIN "PG3"
#define DEFAULT_EXTRUDER_HEATER_PIN "PG5"
#define DEFAULT_EXTRUDER_SENSOR_PIN "PB13"
#define DEFAULT_EXTRUDER_MICROSTEPS 16
#define DEFAULT_EXTRUDER_GEAR_RATIO "50:17"
#define DEFAULT_EXTRUDER_FULL_STEPS_PER_ROTATION 200
#define DEFAULT_EXTRUDER_STEP_DISTANCE -1
#define DEFAULT_EXTRUDER_ROTATION_DISTANCE 6.4
#define DEFAULT_EXTRUDER_NOZZLE_DIAMETER 0.400
#define DEFAULT_EXTRUDER_FILAMENT_DIAMETER 1.750
#define DEFAULT_EXTRUDER_SENSOR_TYPE "EPCOS 100K B57560G104F"
#define DEFAULT_EXTRUDER_CONTROL "pid"
#define DEFAULT_EXTRUDER_PID_KP 15.4404
#define DEFAULT_EXTRUDER_PID_KI 0.728324
#define DEFAULT_EXTRUDER_PID_KD 81.83449
#define DEFAULT_EXTRUDER_MIN_TEMP 0
#define DEFAULT_EXTRUDER_MAX_TEMP 250
#define DEFAULT_EXTRUDER_PRESSURE_ADVANCE 0.03
#define DEFAULT_NOZZLE_DIAMTER 0.4
#define DEFAULT_FILAMENT_DIAMETER 1.75
#define DEFAULT_MAX_CROSS_SECTION 0.64
#define DEFAULT_MAX_E_DIST 50.0
#define DEFAULT_INSTANT_CORNER_V 1.0

// inuput_shaper
#define DEFAULT_SHAPER_FREQ_X 54
#define DEFAULT_SHAPER_TYPE_X "mzv"
#define DEFAULT_SHAPER_FREQ_Y 46
#define DEFAULT_SHAPER_TYPE_Y "mzv"

// resonance_tester
#define DEFAULT_RESONANCE_TESTER_PROBE_POINTS "115,115,20"
#define DEFAULT_RESONANCE_TESTER_ACCEL_CHIP "adxl345"
#define DEFAULT_RESONANCE_TESTER_ACCEL_CHIP_X ""
#define DEFAULT_RESONANCE_TESTER_ACCEL_CHIP_Y ""
#define DEFAULT_RESONANCE_TESTER_MAX_SMOOTHING 0
#define DEFAULT_RESONANCE_TESTER_MIN_FREQ 30
#define DEFAULT_RESONANCE_TESTER_MAX_FREQ 100
#define DEFAULT_RESONANCE_TESTER_ACCEL_PER_HZ 75
#define DEFAULT_RESONANCE_TESTER_HZ_PER_SEC 1

// adxl345
#define DEFAULT_ADXL345_CS_PIN "PD10"
#define DEFAULT_ADXL345_SPI_BUS "spi1"

// bltouch
#define DEFAULT_BLTOUCH_SENSOR_PIN "PF6"
#define DEFAULT_BLTOUCH_CONTROL_PIN "PD22"
#define DEFAULT_BLTOUCH_X_OFFSET 39
#define DEFAULT_BLTOUCH_Y_OFFSET 11
#define DEFAULT_BLTOUCH_Z_OFFSET 0.9
#define DEFAULT_BLTOUCH_SAMPLES 2
#define DEFAULT_BLTOUCH_SAMPLE_RETRACT_DIST 3.0
#define DEFAULT_BLTOUCH_SET_OUTPUT_MODE "OD"

// bed_mesh
// #define DEFAULT_BED_MESH_SPEED 120
// #define DEFAULT_BED_MESH_HORIZONTAL_MOVE_Z 5
// #define DEFAULT_BED_MESH_MESH_MIN "35,6"
// #define DEFAULT_BED_MESH_MESH_MAX

// adc
#define DEFAULT_ADC_MAX 4095
#define DEFAULT_SAMPLE_TIME 8
#define DEFAULT_MAX_STEPPER_ERROR 0.000025

// adc_temp
#define DEFAULT_ADC_TEMP_SAMPLE_TIME 0.001
#define DEFAULT_ADC_TEMP_SAMPLE_COUNT 8
#define DEFAULT_ADC_TEMP_REPORT_TIME 0.300
#define DEFAULT_ADC_TEMP_RANGE_CHECK_COUNT 4
#define DEFAULT_KELVIN_TO_CELSIUS -273.15
#define DEFAULT_MAX_HEAT_TIME 5.0
#define DEFAULT_AMBIENT_TEMP 25.0
#define DEFAULT_PID_PARAM_BASE 255.0

#define DEFAULT_NEVER 10e16

// endstop
#define DEFAULT_REASON_ENDSTOP_HIT 1
#define DEFAULT_REASON_COMMS_TIMEOUT 2
#define DEFAULT_REASON_HOST_REQUEST 3
#define DEFAULT_REASON_PAST_END_TIME 4
#define DEFAULT_HOMING_START_DELAY 0.001
#define DEFAULT_ENDSTOP_SAMPLE_TIME 0.000015
#define DEFAULT_ENDSTOP_SAMPLE_COUNT 4

// gcode
#define DEFAULT_GCODE_COMMAND_QUEUE_SIZE 1024
#define DEFAULT_DO_NOT_MOVE 0x7fffffff
#define DEFAULT_DO_NOT_MOVE_F 10000000.0 // 10000m

// clock
#define DEFAULT_CLOCK 0
#define DEFAULT_SEND_TIME 0.0
#define DEFAULT_RECEIVE_TIME 0.0
#define DEFAULT_RTT_AGE 0.000010 / (60. * 60.)
#define DEFAULT_DECAY 1.0 / 30.
#define DEFAULT_TRANSMIT_EXTRA 0.001
#define DEFAULT_CLOCK_FREQ 200000000.0 //---PARA-G-G-2022---180000000

// MoveQueue
#define DEFAULT_LOOKAHEAD_FLUSH_TIME 0.250 //----G-G-2022-08-11----

// ToolHead
#define DEFAULT_MIN_KIN_TIME 0.100
#define DEFAULT_MOVE_BATCH_TIME 0.500
#define DEFAULT_DRIP_SEGMENT_TIME 0.050
#define DEFAULT_DRIP_TIME 0.100
#define DEFAULT_SDS_CHECK_TIME 0.001 // step+dir+step filter in stepcompress.c

#define DEFAULT_TMC2209_STEPPER_X_UART_PIN "PC4"
#define DEFAULT_TMC2209_STEPPER_X_DIAG_PIN "PG6"
#define DEFAULT_TMC2209_STEPPER_X_RUN_CURRENT 0.800
#define DEFAULT_TMC2209_STEPPER_X_HOLD_CURRENT 0.500
#define DEFAULT_TMC2209_STEPPER_X_STEALTHCHOP_THRESHOLD 999999

#define DEFAULT_TMC2209_STEPPER_Y_UART_PIN "PC4"
#define DEFAULT_TMC2209_STEPPER_Y_DIAG_PIN "PG6"
#define DEFAULT_TMC2209_STEPPER_Y_RUN_CURRENT 0.800
#define DEFAULT_TMC2209_STEPPER_Y_HOLD_CURRENT 0.500
#define DEFAULT_TMC2209_STEPPER_Y_STEALTHCHOP_THRESHOLD 999999

#define DEFAULT_TMC2209_STEPPER_Z_UART_PIN "PC4"
#define DEFAULT_TMC2209_STEPPER_Z_DIAG_PIN "PG6"
#define DEFAULT_TMC2209_STEPPER_Z_RUN_CURRENT 0.800
#define DEFAULT_TMC2209_STEPPER_Z_HOLD_CURRENT 0.500
#define DEFAULT_TMC2209_STEPPER_Z_STEALTHCHOP_THRESHOLD 999999

#define DEFAULT_TMC2209_STEPPER__UART_PIN "PC4"
#define DEFAULT_TMC2209_STEPPER__DIAG_PIN "PG6"
#define DEFAULT_TMC2209_STEPPER__RUN_CURRENT 0.800
#define DEFAULT_TMC2209_STEPPER__HOLD_CURRENT 0.500
#define DEFAULT_TMC2209_STEPPER__STEALTHCHOP_THRESHOLD 999999

#define DEFAULT_TMC2209_EXTRUDER_UART_PIN "PC4"
#define DEFAULT_TMC2209_EXTRUDER_DIAG_PIN "PG6"
#define DEFAULT_TMC2209_EXTRUDER_RUN_CURRENT 0.800
#define DEFAULT_TMC2209_EXTRUDER_HOLD_CURRENT 0.500
#define DEFAULT_TMC2209_EXTRUDER_STEALTHCHOP_THRESHOLD 999999

#define DEFAULT_TMC2209_EXTRUDER1_UART_PIN "PC4"
#define DEFAULT_TMC2209_EXTRUDER1_DIAG_PIN "PG6"
#define DEFAULT_TMC2209_EXTRUDER1_RUN_CURRENT 0.800
#define DEFAULT_TMC2209_EXTRUDER1_HOLD_CURRENT 0.500
#define DEFAULT_TMC2209_EXTRUDER1_STEALTHCHOP_THRESHOLD 999999

#define DEFAULT_TMC2209_EXTRUDER2_UART_PIN "PC4"
#define DEFAULT_TMC2209_EXTRUDER2_DIAG_PIN "PG6"
#define DEFAULT_TMC2209_EXTRUDER2_RUN_CURRENT 0.800
#define DEFAULT_TMC2209_EXTRUDER2_HOLD_CURRENT 0.500
#define DEFAULT_TMC2209_EXTRUDER2_STEALTHCHOP_THRESHOLD 999999

#define DEFAULT_TMC2660_STEPPER_X_CS_PIN "PD14"
#define DEFAULT_TMC2660_STEPPER_X_SPI_BUS "usart1"
#define DEFAULT_TMC2660_STEPPER_X_INTERPOLATE 1
#define DEFAULT_TMC2660_STEPPER_X_RUN_CURRENT 1.000
#define DEFAULT_TMC2660_STEPPER_X_SENSE_RESISTOR 0.051
#define DEFAULT_TMC2660_STEPPER_X_IDLE_CURRENT_PERCENT 20

#define DEFAULT_TMC2660_STEPPER_Y_CS_PIN "PD14"
#define DEFAULT_TMC2660_STEPPER_Y_SPI_BUS "usart1"
#define DEFAULT_TMC2660_STEPPER_Y_INTERPOLATE 1
#define DEFAULT_TMC2660_STEPPER_Y_RUN_CURRENT 1.000
#define DEFAULT_TMC2660_STEPPER_Y_SENSE_RESISTOR 0.051
#define DEFAULT_TMC2660_STEPPER_Y_IDLE_CURRENT_PERCENT 20

#define DEFAULT_TMC2660_STEPPER_Z_CS_PIN "PD14"
#define DEFAULT_TMC2660_STEPPER_Z_SPI_BUS "usart1"
#define DEFAULT_TMC2660_STEPPER_Z_INTERPOLATE 1
#define DEFAULT_TMC2660_STEPPER_Z_RUN_CURRENT 1.000
#define DEFAULT_TMC2660_STEPPER_Z_SENSE_RESISTOR 0.051
#define DEFAULT_TMC2660_STEPPER_Z_IDLE_CURRENT_PERCENT 20

#define DEFAULT_TMC2660_EXTRUDER_CS_PIN "PC17"
#define DEFAULT_TMC2660_EXTRUDER_SPI_BUS "usart1"
#define DEFAULT_TMC2660_EXTRUDER_INTERPOLATE 1
#define DEFAULT_TMC2660_EXTRUDER_RUN_CURRENT 1.000
#define DEFAULT_TMC2660_EXTRUDER_SENSE_RESISTOR 0.051

// bltouch
#define BLTOUCH_SIGNAL_PERIOD 0.020
#define BLTOUCH_MIN_CMD_TIME (5 * BLTOUCH_SIGNAL_PERIOD)
#define BLTOUCH_TEST_TIME (5 * 60.)
#define BLTOUCH_RETRY_RESET_TIME 1.0
#define BLTOUCH_ENDSTOP_REST_TIME 0.001
#define BLTOUCH_ENDSTOP_SAMPLE_TIME 0.000015
#define BLTOUCH_ENDSTOP_SAMPLE_COUNT 4

// tunning tower
#define CANCEL_Z_DELTA 2.0

// manual probe
#define Z_BOB_MINIMUM 0.500
#define BISECT_MAX 0.200

// idle timeout
#define PIN_MIN_TIME 0.100
#define READY_TIMEOUT .500

#define PWM_MAX 2000000

#endif