
name: Build Firmware

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Check out cc-firmware repository
          uses: actions/checkout@v4
          with:
              path: .

        - name: Check out cross-compiler repository
          uses: actions/checkout@v4
          with:
              repository: ${{ github.repository_owner }}/arm-openwrt-linux-gnueabi-gcc
              path: arm-openwrt-linux-gnueabi-gcc

        - name: Build the firmware
          run: |
              ./autoreleash.sh

        - name: Upload firmware artifact
          uses: actions/upload-artifact@v4
          with:
              name: firmware
              path: build/app
